//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC212545_ZC121553.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_2
    {
        public int id { get; set; }
        public string banda { get; set; }
        public string integrantes { get; set; }
        public string album { get; set; }
        public string sencillos { get; set; }
        public byte[] foto { get; set; }
    }
}
